apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertdesk.fullname" . }}-frontend
  labels: {{- include "alertdesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "alertdesk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: 80
